site_name: Установка и настройка Windows
site_description: База знаний
site_author: SergeiAKir  

theme:
  name: material

nav:
  - Главная: index.md
  - Доп Меню: 
      - прочти меня: README.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
