site_name: Помощь в установке и настройке Windows
site_description: База знаний
site_author: SergeiAKir

theme: readthedocs

nav:
  - Главная: index.md
  - Содержание: 
    - Database: 
      - Клиенты: DataBase/Clients.md
    - HardWare:
      - HDD:
        - Тестирование: HardWare/HDD/Тестирование.md
      - Printer:
        - Картридж: HardWare/Printer/Картридж.md
      - USB:
        - Воссстановление: HardWare/USB/Воссстановление.md
  
    - Пример заметки: note1.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
