site_name: Установка и настройка Windows
site_description: База знаний
site_author: SergeiAKir  

theme:
  name: material

nav:
  - Главная: index_0.md
  - Обновления:
      - Блокировка обновления до Windows 11: Блокировка обновления до Windows 11.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
